<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Hash;

class UpdatePasswordRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'random_int' => 'required|numeric',
            'password' => 'required|min:6|confirmed',
            'password_confirmation' => 'required'
        ];
    }

    public function messages()
    {
        return [
            'random_int.numeric' => 'Необходимо ввести цифры',
            'random_int.required' => 'Поле отправки кода обязательно',
            'password.required' => 'Поле пароля обязательно.',
            'password_confirmation.required' => 'Поле подтверждение пароля обязательно.',
        ];
    }

    protected function getValidatorInstance()
    {
        $validate = parent::getValidatorInstance(); // TODO: Change the autogenerated stub

        if (!$validate->fails()) {
            $code = $this->except(['password_confirmation', '_token']);
            $code['password'] = Hash::make($code['password']);
            $this->replace($code);
        }
        return $validate;
    }
}
